config/routes.rb
Rails.application.routes.draw do
  root "urls#new"
  resources :urls, only: [ :new, :create, :index ]
  get "/:short_url", to: "urls#redirect", as: :redirect

  get "urls/report", to: "reports#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
# This url class creates an association between the Url model and the Visit model. The Url model has many visits, and when a Url is destroyed, all of its associated visits are destroyed as well. This is a good example of how to use
class Url < ApplicationRecord
  # each url is associated with many Visit object, if the url is destroyed, all of its associated visits are destroyed
  has_many :visits, dependent: :destroy

  validates :original_url, presence: true
  validate :validate_original_url_format

  validates :short_url, presence: true, uniqueness: true
  validates :title, presence: true

  private

  def validate_original_url_format
    begin
      uri = URI.parse(original_url)
      unless uri.is_a?(URI::HTTP) && uri.host.present?
        errors.add(:original_url, "does not match the required http/https format")
      end
    rescue URI::InvalidURIError
      errors.add(:original_url, "is not a valid URL")
    end
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :url

  validates :ip_address, presence: true
  validates :geolocation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # To retrieve two tables, one with the most visited URLs and another with the number of clicks per URL
  def index
    @reports = aggregate_by_urls
    @click_counts = aggregate_by_clicks
    render :index, status: :ok
  rescue StandardError => e
    render json: { error: e.message }, status: :internal_server_error
  end

  def analytics_url
    @reports = aggregate_by_urls
    render :index, status: :ok
  rescue StandardError => e
    render json: { error: e.message }, status: :internal_server_error
  end

  def click_count
    @click_counts = aggregate_by_clicks
    render :index, status: :ok
  rescue StandardError => e
    render json: { error: e.message }, status: :internal_server_error
  end

  private

  def aggregate_by_clicks
    Visit.joins(:url)
      .select("urls.short_url, MAX(visits.created_at) AS last_visit, COUNT(visits.id) AS total_clicks")
      .group("urls.short_url")
      .order("last_visit DESC")
  end

  def aggregate_by_urls
    Visit.joins(:url)
    .select("urls.short_url, visits.geolocation, visits.created_at AS timestamp")
    .order("timestamp DESC")
  end
end

app/controllers/urls_controller.rb
require "securerandom"
require "base62"
require "nokogiri"
require "geocoder"
require "open-uri"

class UrlsController < ApplicationController
  def new
    @url = Url.new
  end

  def create
    begin
      # Step 1: retrieve the original_url from the form - original_url is valid and not empty
      original_url = params[:url][:original_url]

      # Step 2: fetch the title of the page
      title = fetch_title(original_url)

      # Step 3: Generate a unique short_url with retry limit
      short_url = nil
      loop do
        short_url = generate_unique_short_url
        break unless Url.find_by(short_url: short_url)
      end

      # Step 4: create a new Url object with the original_url, short_url, and title
      @url = Url.new(original_url: original_url, short_url: short_url, title: title)

      # display the error message if the url is not valid
      unless @url.valid?
        render :new, status: :unprocessable_entity
        return
      end
      # Step 5: ensure that short_url is valid and save to the database
      begin
        if @url.save!
          render :show,  status: :created
        else
          render json: { errors: @url.errors.full_messages }, status: :unprocessable_entity
          nil
        end
      rescue ActiveRecord::RecordInvalid => e
        render json: { errors: @url.errors.full_messages }, status: :unprocessable_entity
        nil
      end

      # To handle any exceptions
    rescue StandardError => e
      render json: { errors: e.message }, status: :internal_server_error
      nil
    end
  end

  def index
    redirect_to new_url_path
  end

  # Redirect to the original URL (whether if user clicks or pastes the short URL)
  def redirect
    @url = Url.find_by(short_url: params[:short_url])

    if @url
      redirect_to(@url.original_url, allow_other_host: true)
      performed?

      user_ip = request.remote_ip
      geolocation = Geocoder.search(user_ip)
      country_name = geolocation.first&.country || "Unknown"

      # save details of the visit into visits table
      Visit.create(url: @url, ip_address: user_ip, geolocation: country_name,)
    else
      render file: "#{Rails.root}/public/404.html", status: 404
    end
  end

  private

  def fetch_title(website_link)
    html = URI.open(website_link)
    doc = Nokogiri::HTML(html)
    title = doc.at_css("title").text
    title
  rescue => e
    "Unknown title"
  end

  def generate_unique_short_url
    max_retries = 5
    attempts = 0

    begin
      short_url = Base62.encode(SecureRandom.random_number(1_000_000))
      while Url.find_by(short_url: short_url)
        break if attempts >= max_retries

        short_url = Base62.encode(SecureRandom.random_number(1_000_000))
        attempts += 1
      end

      return short_url if attempts < max_retries
    rescue StandardError => e
      Rails.logger.error "Failed to generate unique short URL: #{e.message}"
    end
    nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
  	<%= link_to 'NotSoTinyUrl', root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
            <%= link_to 'Shorten', root_path,  class: "nav-link" %>
        </li>

        <li class="nav-item">
            <%= link_to 'Report', urls_report_path,  class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title><%= content_for(:title) || "ShortenURL" %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
      <%= render 'home/header' %>
    
    <div class="container">


      <br/>
     <%= yield %>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reports/index.html.erb
<h1>Report</h1>
<br />

<h3>Click count based on url visited</h3>
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th>Short URL</th>
            <th>Last visited</th>
            <th>Click counts</th>
        </tr>
    </thead>
    <tbody>
        <% @click_counts.each do |item| %>
            <tr>
                </td>
                <td><%= "#{root_url}#{item.short_url}"  %></td>
                <td><%= item.last_visit %></td>
                <td><%= item.total_clicks %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br />

<h3>Url visited by timestamp and geolocation</h3>
<table class="table table-striped table-bordered table-hover">
<thead class="thead-dark">
    <tr>
        <th>Short URL</th>
        <th>Geolocation</th>
        <th>Timestamp</th>
    </tr>
</thead>
<tbody>
    <% @reports.each do |report| %>
        <tr>
            </td>
            <td><%= "#{root_url}#{report.short_url}"  %></td>
            <td><%= report.geolocation %></td>
            <td><%= report.timestamp %></td>
        </tr>
    <% end %>
</tbody>
</table>

app/views/urls/new.html.erb
<h2>Enter url that you want to shorten</h2>

<%= form_with model: @url, url: urls_path, local: true do |form|%>
    <div class="field form-group">
        <%= form.text_field :original_url, placeholder: "Enter url to shorten", class:"field form-control p-3" %>
        <div class="d-flex flex-column" style="height: 10px;">   
            <% if @url.errors.any? %>
                <% @url.errors.full_messages_for(:original_url).each do |message| %>
                    <span class="text-danger"><%= message %></span>
                <% end %>
            <% end %>
        </div>
    </div>
    <div  style="display: flex; justify-content: flex-end;">
        <%= form.submit "Shorten URL", class: "btn btn-secondary mt-2 p-3", style:"place-items: end;"  %>
    </div>
<% end %>

app/views/urls/show.html.erb
<h2>Results of NotSoTinyUrl</h2>

<p>Target URL: <span><%= @url.original_url %></span></p>
<p>Short URL: <span><%= link_to "#{root_url}#{@url.short_url}", redirect_path(@url.short_url), target: "_blank" %></span></p>
<p>Title of website: <%= @url.title%> </p>
<%= link_to 'Shorten another URL', new_url_path, class: "btn btn-dark p-3" %> 